services: mongodb
language: go
go:
- 1.5

env:
  global:
    - PATH=$HOME/gopath/bin:$HOME/bin:$PATH
    - ARTIFACTS_WORKING_DIR: $HOME/gopath/bin
    - ARTIFACTS_TARGET_PATHS="$TRAVIS_BRANCH/$TRAVIS_JOB_NUMBER:$TRAVIS_BRANCH/latest"
    - ARTIFACTS_PERMISSIONS=public-read
    - ARTIFACTS_CACHE_CONTROL='public, max-age=315360000'
    - ARTIFACTS_LOG_FORMAT=multiline
    - ARTIFACTS_DEBUG=1

before_script:
  - curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get -d golang.org/x/tools/cmd/cover
  - go get github.com/pierrre/gotestcover
  - cd $HOME/gopath/src/github.com/bulletind/khabar

install: make install

script:
  - go test -v ./...
  - go build -v ./...

after_success:
  - artifacts upload $HOME/gopath/bin/khabar
  - $HOME/gopath/bin/gotestcover -coverprofile=coverage.out ./...
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

notifications:
  email:
    - ops@safetychanger.com

  slack: safetychanger:iBdUKrm6abL7BQNtoIpihFA3
